name: Silent Alert Gold

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Get project files
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install required libraries
        run: pip install -r requirements.txt

      - name: Run silent alert system
        run: python main.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
